videochat/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from videochat.views import register

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('videochatapp.urls')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^register/$', register, name='register')
]

videochatapp/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [

    url(r'^$', views.home, name='home'),
    url(r'^videochat/(?P<roomkey>[a-zA-Z0-9]+)/join$',views.join_videochat,name="joinvideochat"),
    url(r'^videochat/createvideochatroom/$',views.create_videochat_room,name="createvideochatroom"),
    url(r'^videochat/recordconference', views.record_videochat, name="recordconference"),
    url(r'^videochat/(?P<conferenceroomid>\d+)/editconference/', 
                views.edit_videochat_conference, name="editconference"),
    url(r'^videochat/listconferences/$',views.list_videochat,name="listconferences"),
    url(r'^videochat/cancelconference$', views.cancel_videochat, name="cancelconference"),

    url(r'^videochat/start$', views.start_videochat, name="startvideochat"),
    url(r'^videochat/end$', views.end_videochat, name="endvideochat"),
]

videochatapp/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.utils import timezone

# Create your models here.


class ConferenceRoom(models.Model):
    """
    A class to maintain room conference details
    """
    id = models.AutoField(primary_key=True)
    room_key = models.CharField(max_length=32, blank=False, db_index=True)
    title = models.CharField(max_length=255, blank=True, null=True, default=None)
    owner = models.ForeignKey(User)
    # metadata id is ref to metadata field
    metadata_id = models.CharField(max_length=255, blank=True, null=True, default=None)
    # json data for metadata field
    metadata_info = models.TextField()
    start_time = models.DateTimeField(default=timezone.now())
    end_time = models.DateTimeField(default=timezone.now())
    STATUS_CHOICES = (
        ('SCH','Scheduled'),
        ('COM','Completed'),
        ('RUN','Running'),
        ('CAN','Cancelled'),
        ('RES','Rescheduled'),
    )
    status = models.CharField(max_length=3,
                            choices=STATUS_CHOICES,
                            default='SCH')

    created_on = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class ConferenceRoomRoles(models.Model):
    """
    A class to define User roles in ConferenceRoom
    """
    id = models.AutoField(primary_key=True)
    ROLE_CHOICES = (
        ('OWN', 'Owner'),
        ('MOD', 'Moderator'),
        ('PRE', 'Presenter'),
        ('ATD', 'Attendee'),
    )
    role = models.CharField(max_length=3,
                            choices=ROLE_CHOICES,
                            default='OPA')
    created_on = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class ConferenceRoomPrivileges(models.Model):
    """
    A class to define User permissions in ConferenceRoom
    """
    id = models.AutoField(primary_key=True)
    privilege_type = models.CharField(max_length=255, blank=True, null=True, default=None)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class ConferenceRoomRolePrivilegeMap(models.Model):
    """
    A class to define mapping between Roles & permissions
    """
    id = models.AutoField(primary_key=True)
    role = models.ForeignKey(ConferenceRoomRoles)
    privilege = models.ForeignKey(ConferenceRoomPrivileges)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class ConferenceRoomParticipants(models.Model):
    """
    A class to maintain room conference participants list
    """
    id = models.AutoField(primary_key=True)
    conferenceroom = models.ForeignKey(ConferenceRoom)
    user = models.ForeignKey(User)
    role = models.ForeignKey(ConferenceRoomRoles)
    STATUS_CHOICES = (
        ('BLK','Blocked'),
        ('ALW','Allowed'),
    )
    status = models.CharField(max_length=3,
                            choices=STATUS_CHOICES,
                            default='ALW')
    last_seen_heartbeat = models.DateTimeField(null=True)
    special_privilege = models.CharField(max_length=255, blank=True, null=True, default=None)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class ConferenceRoomRecording(models.Model):
    """
    A class to maintain recorded conference videos
    """
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, blank=True, null=True, default=None)
    user = models.ForeignKey(User)
    conferenceroom = models.ForeignKey(ConferenceRoom)
    video_file = models.FileField(upload_to='conferenceroom/mp4/',
                                    blank=True,
                                    null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


# TODO : Remove if not required in future
# class ConferenceRoomConvertedRecording(models.Model):
#     """
#     A class to maintain conveted recorded conference videos
#     """
#     id = models.AutoField(primary_key=True)
#     name = models.CharField(max_length=255, blank=True, null=True, default=None)
#     user = models.ForeignKey(User)
#     conferenceroom = models.ForeignKey(ConferenceRoom)
#     converted_video = models.FileField(upload_to='conferenceroom/mp4/',
#                                         blank=True,
#                                         null=True)
#     created_on = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)

videochat/views.py
from django.shortcuts import render
from django.contrib.auth.models import User 
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.contrib.auth.hashers import make_password

def register(request):
    if request.method == 'POST':
        user = User.objects.filter(username = request.POST.get('username'))
        if user:
            messages.error(request,'User Already Exist.')
            return HttpResponseRedirect('/register',{"messages":messages})
        password = make_password(request.POST.get('password'))
        user  = User(username = request.POST.get('username'),
                    email = request.POST.get('email'),
                    password = password,
                    first_name = request.POST.get('firstname'),
                    last_name = request.POST.get('lastname')
                )
        user.save()
        messages.success(request, 'User Register Successfully.')
        return HttpResponseRedirect('/login',{"messages":messages})
    return render(request,'registration/register.html')

videochatapp/views.py
import json
import random
import string
import datetime
import pytz
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from .models import (ConferenceRoom, ConferenceRoomRoles,
                    ConferenceRoomPrivileges, ConferenceRoomRolePrivilegeMap,
                    ConferenceRoomParticipants, ConferenceRoomRecording)
import subprocess
from django.conf import settings
from django.core.files import File
import os

# Create your views here.
def home(request):
    """
    Function to show home page
    """
    return render(request, 'videochatapp/home.html')

@login_required(login_url='/login/')
def join_videochat(request, roomkey):
    """
    Function to show join videochat room
    """
    try:
        conferenceroom = ConferenceRoom.objects.get(room_key=roomkey)
    except ConferenceRoom.DoesNotExist:
        return HttpResponse("Conference is does not exists.")
    try:
        is_participant = ConferenceRoomParticipants.objects.get(conferenceroom=conferenceroom,user=request.user)
    except ConferenceRoomParticipants.DoesNotExist:
        return HttpResponse("Your are not Conference Participant")
    try:
        if conferenceroom.status != 'RUN':
            if is_participant.role.role == 'OWN':
                conferenceroom.status = 'RUN'
                conferenceroom.save()
            elif conferenceroom.status == 'COM':
                return HttpResponse("Conference is ended.")
            elif conferenceroom.status == 'CAN':
                return HttpResponse("Conference is cancelled.")
            elif conferenceroom.status == 'RES':
                return HttpResponse("Conference is rescheduled.")
            else:
                return HttpResponse("Conference is yet to start.")
    except:
        return HttpResponse("Something went wrong")
    return render(request, 'videochatapp/videochat.html',{'roomkey':roomkey})

@login_required(login_url='/login/')
def start_videochat(request):
    """
    Function to update status of videochat room as running
    """
    if request.method == 'POST':
        roomkey = request.POST.get('roomkey', None)
        user = request.user
        context = {
            'msg': 'Conference has started',
            'status': 'RUN'
        }
        try:
            conferenceroom = ConferenceRoom.objects.get(room_key=roomkey)
        except ConferenceRoom.DoesNotExist:
            return HttpResponse(status=404)
        try:
            if conferenceroom.owner == user:
                conferenceroom.status = 'RUN'
                conferenceroom.save()
                return HttpResponse(json.dumps(context), content_type='application/json',status=200)
            elif conferenceroom.status == 'RUN':
                context['msg'] = 'Conference is running'
                return HttpResponse(json.dumps(context), content_type='application/json',status=200)
            elif conferenceroom.status in ['CAN', 'RES']:
                context['msg'] = 'Conference does not exist anymore'
                context['status'] = 'CAN'
                return HttpResponse(json.dumps(context), content_type='application/json',status=200)
            elif conferenceroom.status == 'COM':
                context['msg'] = 'Conference is ended'
                context['status'] = 'COM'
                return HttpResponse(json.dumps(context), content_type='application/json',status=200)
            else:
                context['msg'] = 'Conference is not started yet.'
                context['status'] = 'SCH'
                return HttpResponse(json.dumps(context), content_type='application/json',status=200)
        except:
            return HttpResponse(status=400)
    else:
        return HttpResponse(status=400)

@login_required(login_url='/login/')
def end_videochat(request):
    """
    Function to update status of videochat room as ended
    """
    if request.method == 'POST':
        roomkey = request.POST.get('roomkey', None)
        user = request.user
        try:
            conferenceroom = ConferenceRoom.objects.get(room_key=roomkey)
        except ConferenceRoom.DoesNotExist:
            return HttpResponse(status=404)
        try:
            context = {
                'msg': 'Conference has ended',
                'status': 'COM'
            }
            if conferenceroom.owner == user:
                conferenceroom.status = 'COM'
                conferenceroom.save()
                return HttpResponse(json.dumps(context), content_type='application/json',status=200)
            else:
                context['msg'] = 'You have left conference'
                return HttpResponse(json.dumps(context), content_type='application/json',status=200)
        except:
            return HttpResponse(status=400)
    else:
        return HttpResponse(status=400)

@login_required(login_url='/login/')
def create_videochat_room(request):
    """
    Function to create videochat room
    """
    if request.method == 'POST':
        try:
            data = json.loads(request.POST.get('data'))
            start_time = data['starttime']
            start_time = datetime.datetime.strptime(start_time,"%Y/%m/%d %H:%M")
            start_time = pytz.utc.localize(start_time)
            end_time = data['endtime']
            end_time = datetime.datetime.strptime(end_time,"%Y/%m/%d %H:%M")
            end_time = pytz.utc.localize(end_time)
            conf_title = data['title']
            del data['starttime']
            del data['endtime']
            del data['title']
            if not conf_title:
                conf_title = "Default title"
            key_value = ''.join([random.choice(string.ascii_letters + string.digits) for n in xrange(32)])
            conference_room = ConferenceRoom(room_key = key_value,
                                            title = conf_title,
                                            owner = request.user,
                                            start_time = start_time,
                                            end_time = end_time
                                            )
            conference_room.save()

            for user_id,user_dict in data.iteritems():
                user = User.objects.get(id = user_id)
                user_role = user_dict['role']
                special_privilege = ','.join(str(e) for e in user_dict['special_privilege'])
                user_role = ConferenceRoomRoles.objects.get(role = user_role)
                if user and user_role:
                    conference_room_participants = ConferenceRoomParticipants(
                                                    conferenceroom=conference_room,
                                                    user=user,
                                                    role=user_role,
                                                    special_privilege=special_privilege
                                                )
                    conference_room_participants.save()

            owner_role = ConferenceRoomRoles.objects.get(role='OWN')        
            conference_room_participants = ConferenceRoomParticipants(
                                                    conferenceroom=conference_room,
                                                    user=request.user,
                                                    role=owner_role
                                            )
            conference_room_participants.save()
            response = {"message":"Conference room is created successfully."}
            return HttpResponse(json.dumps(response), 
                            content_type='application/json')
        except Exception as e:
            response = {"message":"oops something went wrong..."}
            return HttpResponse(json.dumps(response), 
                            content_type='application/json')

    else:
        try:
            # Get all participants users excluding current user
            participants = User.objects.all().exclude(id=request.user.id)
        except:
            raise
        try:
            # Get all user roles
            participants_roles = ConferenceRoomRoles.objects.all().exclude(role='OWN')
            participants_privileges = ConferenceRoomPrivileges.objects.all()
            participants_role_privilege_map = ConferenceRoomRolePrivilegeMap.objects.all()
            new_participants_roles = []
        except:
            raise

        for role in participants_roles:
            default_privileges = []
            temp_default_privileges = role.conferenceroomroleprivilegemap_set.all()
            for privilege in temp_default_privileges:
                default_privileges.append(str(privilege.privilege.privilege_type))
            role.default_privileges = default_privileges
            new_participants_roles.append(role)
            

        context = {
            'participants': participants,
            'participants_roles' : new_participants_roles,
            'participants_privileges' : participants_privileges,
            'participants_role_privilege_map' : participants_role_privilege_map
        }

        return render(request, 'videochatapp/create_videochat_room.html',context)

@login_required(login_url='/login/')
def list_videochat(request):
    """ 
    Function to list all conferences of requested user 
    """
    conference_context = {}
    conference_participants= ConferenceRoomParticipants.objects.filter(user=request.user)
    data_list = list()
    edit_btn_privilege = ['remove_participant', 'block_participant',
                         'add_participant', 'participant_management',
                         'event_management']
    cancel_btn_privilege = ['event_management']
    for conference_participant in conference_participants:
        if conference_participant.conferenceroom.status not in ['CAN']:

videochatapp/templates/videochatapp/create_videochat_room.html
{% extends 'videochatapp/base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'videochatapp/css/create_videochat_room.css' %}"/>
{% endblock %} 
{% block content %}
    <div class="container">
        <div class="table-responsive">
            <form id="createconference" method="POST">
                {% csrf_token %}
                <div>
                    <div class="form-group">
                        <lable><b>Add Event Title</b></label>
                        <input type="text" class="form-control conf-title" name="conf-title" placeholder="Add Event Title" required>
                    </div>
                </div>
                <table class="table results conference-table-data">
                    <thead>
                        <td><h3>Sr No</h3>
                        <td>
                        <td><h3>Participant
                        <td><h3>Participant Type
                        <td><h3>Participant Role
                        <td><h3>Extra Privilege</h3>
                    </thead>
                    <tbody>
                        {% for participant in participants %}
                            <tr class="participant-details">
                                <td>{{ forloop.counter }}</td>
                                <td class="content-middle participant-checkbox">
                                    <input type="checkbox" class="selected-participant" name="{{ participant.id }}" value="{{ participant.email }}">
                                </td>
                                <td class="participant-email">
                                    <span>{{ participant.email }}</span>
                                </td>
                                <td class="participant-role">
                                    {% if participant.is_staff %}
                                        <span>Staff</span>
                                    {% else %}
                                        <span>Student</span>
                                    {% endif %}
                                </td>
                                <td class="participant-roles-listing">
                                    <select class="form-control selected-participant-role" name="roles" onload="setDefaultPrivilege($(this));">
                                        {% for role in participants_roles %}
                                            <option value="{{ role.role }}" defaultprivileges="{{role.default_privileges}}">{{ role.get_role_display }}</option>
                                        {% endfor %}
                                    </select>
                                </td>
                                <td class="participant-privileges-listing">
                                    <select class="form-control selected-participant-privilege" name="privilege[]" multiple>
                                        {% for privilege in participants_privileges %}
                                            <option value="{{ privilege.privilege_type }}">{{ privilege.privilege_type |title }}</option>
                                        {% endfor %}
                                    </select>   
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="form-group">
                    <span>Start Time</span><input id="start-time" name="start-time" class="form-control input-style" type="text" required> 
                    <span>End Time<span><input id="end-time" name="end-time" class="form-control input-style" type="text" required>
                </div>
                <div class="form-group">
                    <input id="create-bt" class="btn btn-primary" type = "submit" name="submit" value="Create Conference">
                </div>
            </form>
        </div>
    </div>
{% endblock %}
{% block bottomcontent %}
<script src="{% static 'videochatapp/js/create_videochat_room.js' %}"></script>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.18/jquery.datetimepicker.css"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.18/jquery.datetimepicker.full.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.18/jquery.datetimepicker.full.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.18/jquery.datetimepicker.js"></script>
<script>
    jQuery('#start-time').datetimepicker();
    jQuery('#end-time').datetimepicker();
</script>
{% endblock %}

videochatapp/templates/videochatapp/edit_videochat_room.html
{% extends 'videochatapp/base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'videochatapp/css/create_videochat_room.css' %}"/>
{% endblock %} 
{% block content %}
    <div class="container">
        <div class="table-responsive">
            <form id="editconference" method="POST">
                {% csrf_token %}
                <table class="table results conference-table-data">
                    <thead>
                        {% if user_listing_privilege %}
                            <td><h3>Sr No</h3>
                            <td>
                            <td><h3>Participant
                            <td><h3>Participant Type
                            <td><h3>Participant Role
                            {% if manage_privilege_for_user_privilege %}
                                <td><h3>Extra Privilege</h3>
                            {% endif %}
                        {% endif %}
                    </thead>
                    <tbody>
                        {% if event_schedule_privilege %}
                            <tr>
                                <td colspan=3>Add Event Title</td>
                                <td colspan=3>
                                    <div class="form-group">
                                        <input type="text" class="form-control conf-title" name="conf-title" placeholder="Add Event Title" value="{{ conferenceroom.title | title }}" required>
                                    </div>
                                </td>
                            </tr>
                        {% endif %}

                        {% if user_listing_privilege %}
                            {% for participant in participants %}
                                <tr class="participant-details">
                                    <td>{{ forloop.counter }}</td>
                                    <td class="content-middle participant-checkbox">
                                        {% if participant.role %}
                                            <input type="checkbox" class="selected-participant" name="{{ participant.id }}" value="{{ participant.email }}" checked>
                                        {% else %}
                                            <input type="checkbox" class="selected-participant" name="{{ participant.id }}" value="{{ participant.email }}">
                                        {% endif %}
                                    </td>
                                    <td class="participant-email">
                                        <span>{{ participant.email }}</span>
                                    </td>
                                    <td class="participant-role">
                                        {% if participant.is_staff %}
                                            <span>Staff</span>
                                        {% else %}
                                            <span>Student</span>
                                        {% endif %}
                                    </td>
                                    <td class="participant-roles-listing">
                                        <select class="form-control selected-participant-role" name="roles">
                                            {% for role in participants_roles %}
                                                {% if participant.role and participant.role == role.role %}
                                                    <option value="{{ role.role }}" selected="selected" defaultprivileges="{{role.default_privileges}}">{{ role.get_role_display }}</option>
                                                {% else %}
                                                    <option value="{{ role.role }}" defaultprivileges="{{role.default_privileges}}">{{ role.get_role_display }}</option>
                                                {% endif %}
                                            {% endfor %}
                                        </select>   
                                    </td>
                                    {% if manage_privilege_for_user_privilege %}
                                        <td class="participant-privileges-listing">
                                            <select class="form-control selected-participant-privilege" name="privilege[]" multiple>
                                                {% for privilege in participants_privileges %}
                                                    {% if participant.special_privilege and privilege.privilege_type in participant.special_privilege %}
                                                        <option value="{{ privilege.privilege_type }}" selected="selected">{{ privilege.privilege_type |title }}</option>
                                                    {% else %}
                                                        <option value="{{ privilege.privilege_type }}">{{ privilege.privilege_type |title }}</option>
                                                    {% endif %}
                                                {% endfor %}
                                            </select>   
                                        </td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                        {% endif %}
                    </tbody>
                </table>
                {% if event_schedule_privilege %}
                    <div class="form-group">
                        <span>Start Time</span><input id="start-time" name="start-time" class="form-control input-style" type="text" value="{{ conferenceroom.start_time|date:'Y/m/d H:i' }}" required> 
                        <span>End Time<span><input id="end-time" name="end-time" class="form-control input-style" type="text" value="{{ conferenceroom.end_time|date:'Y/m/d H:i' }}" required>
                    </div>
                {% endif %}
                <div class="form-group">
                    <input id="create-bt" rel={{conferenceroom.id}} class="btn btn-primary" type="submit" name="submit" value="Update Conference" data-event_schedule_privilege="{{event_schedule_privilege}}" data-user_listing_privilege="{{user_listing_privilege}}">
                </div>
            </form>
        </div>
    </div>
{% endblock %}
{% block bottomcontent %}
<script src="{% static 'videochatapp/js/create_videochat_room.js' %}"></script>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.18/jquery.datetimepicker.css"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.18/jquery.datetimepicker.full.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.18/jquery.datetimepicker.full.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.18/jquery.datetimepicker.js"></script>
<script>
    jQuery('#start-time').datetimepicker();
    jQuery('#end-time').datetimepicker();
</script>
{% endblock %}

videochatapp/templates/videochatapp/list_conferences.html
{% extends 'videochatapp/base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'videochatapp/css/list_conferences.css' %}"/>
{% endblock %} 

{% block content %}
    <div class="container">
    <div class="table-responsive">
        <table class="table results">
        <tbody>
        {% for data in data_list %}
            <tr>
                <td class="content-middle">
                    <h3>{{ forloop.counter }}</h3>           
                </td>
                <td>
                    {% if data.conference.status == 'CAN' %}
                        <h3 class="inline-heading"><a href="javascript:void(0);">{{ data.conference.title |title }}</a></h3>
                    {% else %}
                        <h3 class="inline-heading"><a href="{% url 'joinvideochat' roomkey=data.conference.room_key %}">{{ data.conference.title |title }}</a></h3>
                    {% endif %}
                </td>
                <td>
                    <p class="margin-tp para-content"><strong>Conference Status:</strong>{{ data.conference.get_status_display | title }}</p>
                </td>
                <td>
                    <p class="margin-tp para-content"><strong>Start Time:</strong>{{ data.start_time }}</p>
                </td>
                <td>
                    <p class="margin-tp para-content"><strong>End Time:</strong>{{ data.end_time }}</p>
                </td>
                <td>
                    <p class="margin-tp para-content"><strong>No of Participant:</strong>{{ data.no_participants}}</p>
                </td>
                <td>
                    <p class="margin-tp para-content"><strong>Role:</strong>{{ data.role.get_role_display }}</p>
                </td>
                {% if data.show_edit_btn or data.show_cancel_btn %}
                    <td>
                        <p class="margin-tp para-content">
                            {% if data.show_edit_btn %}
                                <button class="edit-conference" id="{{data.conference.id}}">Edit</button>
                            {% endif %}
                            {% if data.show_cancel_btn %}
                                <button class="cancel-conference" id="{{data.conference.id}}">Cancel</button>
                            {% endif %}
                        </p>
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
        </table>
    </div>  
</div>

{% endblock %}
{% block bottomcontent %}
<script src="{% static 'videochatapp/js/list_videochat_room.js' %}"></script>
{% endblock %}